app/routes/tasks.py
from datetime import datetime
from decimal import Decimal
from io import BytesIO
from typing import Dict, List, Tuple, Union

from flask import Blueprint, flash, redirect, render_template, request, send_file, url_for
from flask_login import login_required
from werkzeug.wrappers import Response

from app.db import DatabaseManager
from app.utils import MESSAGES, generate_report, permission_required

Tasks = List[Dict[str, Union[str, Decimal]]]
GroupedData = Dict[str, Dict[str, Union[str, Dict[str, Decimal]]]]

tasks_bp: Blueprint = Blueprint("tasks", __name__, url_prefix="/tasks")
db_manager: DatabaseManager = DatabaseManager()


@tasks_bp.route("/table", methods=["GET"])
@login_required
def tasks_table() -> Union[str, Response]:
    args: Dict[str, str] = {
        "departments": request.args.getlist("departments[]"),
        "start_date": request.args.get("start_date"),
        "end_date": request.args.get("end_date"),
        "employee_data": request.args.get("employee_data"),
        "order_number": request.args.get("order_number"),
        "work_name": request.args.get("work_name"),
        "order_name": request.args.get("order_name"),
    }

    tasks: Tasks = db_manager.tasks.get_tasks(**args)
    departments: List[str] = db_manager.employees.get_departments()

    # if request.args.get("export"):
    #     file: BytesIO = generate_report(tasks)
    #     return send_file(file, as_attachment=True, download_name="report.xlsx")

    today: str = datetime.today().strftime("%Y-%m-%d")
    context: Dict[str, Union[str, Tasks]] = {
        "tasks": tasks,
        "departments": departments,
        "today": today,
    }
    return render_template("tasks/tasks_table.html", **context)


@tasks_bp.route("/add", methods=["GET", "POST"])
@login_required
@permission_required(["advanced", "standard"])
def add_task() -> Union[str, Response]:
    if request.method == "POST":
        employee_data: str = request.form.get("employee_data")
        operation_date: str = request.form.get("operation_date")
        order_names: List[str] = request.form.getlist("order_name[]")
        order_numbers: List[str] = request.form.getlist("order_number[]")

        if not operation_date:
            operation_date: str = datetime.now().strftime("%Y-%m-%d")

        employee_details: Tuple[str, str] = db_manager.employees.get_employee_details(employee_data)
        employee_name, personnel_number = employee_details

        employee_department: str = db_manager.employees.get_employee_department(personnel_number)
        employee_category: str = db_manager.employees.get_employee_category(personnel_number)

        grouped_data: GroupedData = {
            order_number: {
                "order_name": order_name,
                "works": {
                    work_name.split("][")[1].rstrip("]"): Decimal(spent_hours)
                    for work_name, spent_hours in request.form.items()
                    if spent_hours and work_name.startswith(f"work_hours[{order_number}]")
                },
            }
            for order_number, order_name in zip(order_numbers, order_names)
        }

        total_spent_hours: Decimal = Decimal(0)

        for order_data in grouped_data.values():
            for spent_hours in order_data["works"].values():
                if spent_hours < Decimal(0):
                    flash(message=MESSAGES["tasks"]["hours_less_than_zero"], category="error")
                    return render_template("tasks/add_task.html")
                total_spent_hours += spent_hours

        if total_spent_hours > Decimal(8.25):
            flash(message=MESSAGES["tasks"]["hours_exceed_limit"], category="error")
            return render_template("tasks/add_task.html")

        for order_number, order_data in grouped_data.items():
            for work_name, spent_hours in order_data["works"].items():
                args: Dict[str, Union[str, Decimal]] = {
                    "employee_name": employee_name,
                    "personnel_number": personnel_number,
                    "department": employee_department,
                    "work_name": work_name,
                    "hours": spent_hours,
                    "order_number": order_number,
                    "order_name": order_data["order_name"],
                    "operation_date": operation_date,
                    "employee_category": employee_category,
                }
                db_manager.tasks.add_task(**args)
        flash(message="Задания успешно добавлены.", category="info")
        return redirect(url_for("tasks.add_task"))
    return render_template("tasks/add_task.html")


@tasks_bp.route("/edit/<int:task_id>", methods=["GET", "POST"])
@login_required
@permission_required(["advanced", "standard"])
def edit_task(task_id: int) -> Union[str, Response]:
    task_data: Dict[str, Union[str, Decimal]] = db_manager.tasks.get_task_data_by_id(task_id)

    context: Dict[str, Union[str, Decimal]] = {
        "employee_name": task_data["employee_name"],
        "personnel_number": task_data["personnel_number"],
        "operation_date": task_data["operation_date"],
        "hours": task_data["hours"],
        "order_name": task_data["order_name"],
        "order_number": task_data["order_number"],
        "work_name": task_data["work_name"],
    }

    if request.method == "POST":
        employee_data: str = request.form.get("employee_data")
        operation_date: str = request.form.get("operation_date")
        hours: str = request.form.get("hours")
        order_name: str = request.form.get("order_name")
        order_number: str = request.form.get("order_number")
        work_name: str = request.form.get("work_name")

        employee_details: Tuple[str, str] = db_manager.employees.get_employee_details(employee_data)

        if employee_details is None:
            flash(message=MESSAGES["employees"]["invalid_employee_format"], category="warning")
            context: Dict[str, str] = {
                "operation_date": operation_date,
                "hours": hours,
                "order_name": order_name,
                "order_number": order_number,
                "work_name": work_name,
            }
            return render_template("tasks/edit_task.html", **context)

        employee_name, personnel_number = employee_details

        if not db_manager.employees.employee_exists(personnel_number):
            flash(message=MESSAGES["employees"]["employee_not_found"], category="warning")
            context: Dict[str, str] = {
                "employee_name": employee_name,
                "personnel_number": personnel_number,
                "operation_date": operation_date,
                "hours": hours,
                "order_name": order_name,
                "order_number": order_number,
                "work_name": work_name,
            }
            return render_template("tasks/edit_task.html", **context)

        free_hours: Decimal = db_manager.employees.get_employee_free_hours(personnel_number, operation_date)

        if Decimal(hours) > free_hours + context["hours"]:
            free_hours: Decimal = free_hours + context["hours"]
            message: str = MESSAGES["employees"]["exceeded_hours"].format(employee_data, free_hours)
            flash(message=message, category="warning")
            context: Dict[str, str] = {
                "employee_name": employee_name,
                "personnel_number": personnel_number,
                "operation_date": operation_date,
                "hours": hours,
                "order_name": order_name,
                "order_number": order_number,
                "work_name": work_name,
            }
            return render_template("tasks/edit_task.html", **context)

        args: Dict[str, Union[str, Decimal]] = {
            "task_id": task_id,
            "employee_name": employee_name,
            "personnel_number": personnel_number,
            "hours": Decimal(hours),
            "order_name": order_name,
            "order_number": order_number,
            "operation_date": operation_date,
            "work_name": work_name,
        }
        db_manager.tasks.update_task(**args)

        params: Dict[str, str] = {
            "departments[]": request.args.getlist("departments[]"),
            "start_date": request.args.get("start_date"),
            "end_date": request.args.get("end_date"),
            "employee_data": request.args.get("employee_data"),
            "order_number": request.args.get("order_number"),
            "work_name": request.args.get("work_name"),
            "order_name": request.args.get("order_name"),
        }
        return redirect(url_for("tasks.tasks_table", **params))
    return render_template("tasks/edit_task.html", **context)


@tasks_bp.route("/delete/<int:task_id>", methods=["POST"])
@login_required
@permission_required(["advanced", "standard"])
def delete_task(task_id: str) -> Response:
    params: Dict[str, str] = {
        "departments[]": request.form.getlist("departments[]"),
        "start_date": request.form.get("start_date"),
        "end_date": request.form.get("end_date"),
        "employee_data": request.form.get("employee_data"),
        "order_number": request.form.get("order_number"),
        "work_name": request.form.get("work_name"),
        "order_name": request.form.get("order_name"),
    }
    db_manager.tasks.delete_task(task_id)
    return redirect(url_for("tasks.tasks_table", **params))

app/templates/tasks/add_task.html
{% extends "base.html" %}

{% block title %}Добавление заданий{% endblock title %}

{% block content %}
    <div class="add-task-container">
        <p class="paragraph">Добавление заданий</p>
        <form method="POST" id="tasks-form">
            <div class="form-group">
                <i class="fas fa-user" style="left: 14px;"></i>
                <input
                    type="text"
                    name="employee_data"
                    class="employee-data"
                    placeholder="ФИО работника"
                    autocomplete="off"
                    value="{{ employee_data | default('') }}"
                    required
                />
                <div class="employee-data-suggestions suggestions-list"></div>
            </div>

            <div class="form-group">
                <i class="fas fa-calendar-alt" style="left: 14px;"></i>
                <input
                    type="date"
                    name="operation_date"
                    value="{{ operation_date | default('') }}"
                    style="cursor: pointer;"
                />
            </div>

            <div id="tasks-container">
                <div class="task-fields">
                    <p class="task-number">Блок &#8470;1</p>
                    <div class="form-group">
                        <i class="fas fa-cogs" style="left: 14px;"></i>
                        <input
                            type="text"
                            name="order_name[]"
                            class="order-name"
                            placeholder="Наименование заказа"
                            autocomplete="off"
                            required
                        />
                        <div class="order-name-suggestions suggestions-list"></div>
                    </div>
                    <div class="form-group">
                        <i class="fas fa-hashtag" style="left: 14px;"></i>
                        <input
                            type="text"
                            name="order_number[]"
                            value="{{ order_number }}"
                            class="order-number"
                            placeholder="Номер заказа"
                            autocomplete="off"
                            required
                        />
                        <div class="order-number-suggestions suggestions-list"></div>
                    </div>
                    <div class="add-task-buttons-container">
                        <button type="button" class="default-button add-works-button">Добавить работы</button>
                        <button type="button" class="default-button delete-form-task-button">Удалить блок</button>
                    </div>
                    <hr>
                </div>
            </div>
            <div class="add-task-buttons-container">
                <button type="button" id="add-form-task-button" class="default-button add-form-task-button">Добавить блок</button>
                <button type="submit" class="default-button save-form-tasks-button">Сохранить задания</button>
            </div>
            <div id="hidden-work-hours-container" style="display: none;"></div>
        </form>
    </div>

    <div class="flashed-messages" style="width: 640px;">
        {% for category, message in get_flashed_messages(with_categories=true) %}
            <div class="{{ category }}" id="message">
                {{ message }}
            </div>
        {% endfor %}
    </div>

    <div class="modal-container">
        <div class="modal-content">
            <span class="close-modal-button"><i class="fas fa-times"></i></span>
            <p class="modal-text">Вы уверены, что хотите удалить блок?</p>
            <div class="modal-buttons">
                <button id="confirm-delete-task" class="btn btn-danger">Удалить</button>
                <button id="cancel-delete-task" class="btn btn-secondary">Отмена</button>
            </div>
        </div>
    </div>

    <div class="works-modal-container" style="display: none;">
        <div class="works-modal-content">
            <span class="close-works-modal"><i class="fas fa-times"></i></span>
            <div id="works-modal-title"></div>
            <table id="works-table" class="works-modal-table">
                <thead>
                    <tr>
                        <th>Наименование работы</th>
                        <th>Плановая трудоемкость, ч</th>
                        <th>Фактическая трудоемкость, ч</th>
                        <th>Остаточная трудоемкость, ч</th>
                        <th>Затраченное время, ч</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
            <button id="save-works" class="btn" style="margin-top: 20px;">Закрыть</button>
        </div>
    </div>
{% endblock content %}

app/templates/tasks/edit_task.html
{% extends "base.html" %}

{% block title %}Редактирование задания{% endblock %}

{% block content %}
    <div class="edit-task-container">
        <p class="paragraph">Редактирование задания</p>
        <form method="POST">
            <div class="form-group">
                <i class="fas fa-user" style="left: 14px;"></i>
                <input
                    type="text"
                    name="employee_data"
                    class="employee-data"
                    placeholder="ФИО работника"
                    value="{{ '{} ({})'.format(employee_name, personnel_number) if employee_name and personnel_number else '' }}"
                    required
                />
                <div class="employee-data-suggestions suggestions-list"></div>
            </div>

            <div class="form-group">
                <i class="fas fa-calendar-alt" style="left: 14px;"></i>
                <input
                    type="date"
                    name="operation_date"
                    value="{{ operation_date }}"
                    required
                />
            </div>

            <div class="task-fields">
                <div class="form-group">
                    <i class="fas fa-clock" style="left: 14px;"></i>
                    <input
                        type="number"
                        name="hours"
                        min="0"
                        max="8.25"
                        step="0.01"
                        placeholder="Часы работы"
                        value="{{ hours }}"
                        required
                    />
                </div>

                <div class="form-group">
                    <i class="fas fa-cogs" style="left: 14px;"></i>
                    <input
                        type="text"
                        name="order_name"
                        class="order-name"
                        placeholder="Наименование заказа"
                        value="{{ order_name }}"
                        required
                    />
                    <div class="order-name-suggestions suggestions-list"></div>
                </div>

                <div class="form-group">
                    <i class="fas fa-hashtag" style="left: 14px;"></i>
                    <input
                        type="text"
                        name="order_number"
                        class="order-number"
                        placeholder="Номер заказа"
                        value="{{ order_number }}"
                        required
                    />
                    <div class="order-number-suggestions suggestions-list"></div>
                </div>

                <div class="form-group">
                    <i class="fas fa-tools" style="left: 14px;"></i>
                    <input
                        type="text"
                        name="work_name"
                        class="work-name"
                        placeholder="Наименование работы"
                        value="{{ work_name }}"
                        required
                    />
                </div>
            </div>

            {% set params = {
                "department": request.args.get("department"),
                "start_date": request.args.get("start_date"),
                "end_date": request.args.get("end_date"),
                "employee_data": request.args.get("employee_data"),
                "order_number": request.args.get("order_number"),
                "work_name": request.args.get("work_name"),
                "order_name": request.args.get("order_name"),
            } %}

            <div class="edit-task-buttons-container">
                <button type="submit" class="default-button save-task-button">Сохранить изменения</button>
                <a href="{{ url_for('tasks.tasks_table', **params) }}" class="default-button cancel-button">Отмена</a>
            </div>
        </form>
    </div>

    <div class="flashed-messages" style="width: 640px;">
        {% for category, message in get_flashed_messages(with_categories=true) %}
            <div class="{{ category }}" id="message">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/tasks/tasks_table.html
{% extends "base.html" %}

{% block title %}Все задания{% endblock title %}

{% block content %}
    <div class="tasks-container">
        <form method="GET" action="{{ url_for('tasks.tasks_table') }}">
            <div class="filter-container">
                <div class="dropdown">
                    <label class="dropdown-title">Фильтр по наименованию подразделения</label>
                    <input type="checkbox" id="toggle-dropdown">

                    {% set selected_departments = request.args.getlist("departments[]") %}

                    <label for="toggle-dropdown" class="dropdown-label" id="dropdown-text">
                        <span id="dropdown-selected-text">
                            {% if selected_departments %}
                                {{ selected_departments | join(", ") }}
                            {% else %}
                                Все
                            {% endif %}
                        </span>
                        <i class="fa-solid fa-chevron-down dropdown-icon"></i>
                    </label>

                    <div class="dropdown-content" id="dropdown-list">
                        {% for department in departments %}
                            <label>
                                <input
                                    type="checkbox"
                                    name="departments[]"
                                    value="{{ department }}"
                                    {% if department in selected_departments %}checked{% endif %}>
                                {{ department }}
                            </label>
                        {% endfor %}
                    </div>
                </div>

                <div class="filter-item">
                    <label>Фильтр по дате</label>
                    <div class="date-filters">
                        <input
                            type="date"
                            name="start_date"
                            value="{{ request.args.get('start_date', today) }}"
                            style="cursor: pointer;"
                        />
                        <span style="margin: 10px;">по</span>
                        <input
                            type="date"
                            name="end_date"
                            value="{{ request.args.get('end_date', today) }}"
                            style="cursor: pointer;"
                        />
                    </div>
                </div>

                <div class="filter-item">
                    <label>Фильтр по ФИО сотрудника</label>
                    <div>
                        <i class="fas fa-user"></i>
                        <input type="text" name="employee_data" value="{{ request.args.get('employee_data', '') }}"
                            class="employee-data" placeholder="ФИО работника" autocomplete="off">
                        <div class="employee-data-suggestions suggestions-list"></div>
                    </div>
                </div>

                <div class="filter-item">
                    <label>Фильтр по номеру заказа</label>
                    <div>
                        <i class="fas fa-hashtag"></i>
                        <input type="text" name="order_number" value="{{ request.args.get('order_number', '') }}"
                            class="order-number" placeholder="Номер заказа" autocomplete="off">
                        <div class="order-number-suggestions suggestions-list"></div>
                    </div>
                </div>

                <div class="filter-item">
                    <label>Фильтр по наименованию работы</label>
                    <div>
                        <i class="fas fa-hammer"></i>
                        <input type="text" name="work_name" value="{{ request.args.get('work_name', '') }}"
                            class="work-name" placeholder="Наименование работы" autocomplete="off">
                        <div class="work-name-suggestions suggestions-list"></div>
                    </div>
                </div>

                <div class="filter-item">
                    <label>Фильтр по наименованию заказа</label>
                    <div>
                        <i class="fas fa-cogs"></i>
                        <input type="text" name="order_name" value="{{ request.args.get('order_name', '') }}"
                            class="order-name" placeholder="Наименование заказа" autocomplete="off">
                        <div class="order-name-suggestions suggestions-list"></div>
                    </div>
                </div>
            </div>

            <div class="filter-buttons-container">
                <button type="submit" class="reset-filters-button">
                    <i class="fas fa-eraser"></i>Сбросить фильтры
                </button>
                <button type="submit" class="apply-filters-button">
                    <i class="fas fa-play"></i>Применить фильтры
                </button>
                {# <button type="submit" name="export" value="true" class="export-report-button">
                    <i class="fas fa-arrow-down"></i>Выгрузить отчет
                </button> #}
            </div>
        </form>

        <div class="sticky-header-spacer"></div>

        <table>
            <thead>
                <tr>
                    <th style="border: none;">&#8470;</th>
                    <th>ФИО сотрудника</th>
                    <th>Таб. номер</th>
                    <th>Роль сотрудника</th>
                    <th>Наименование подразделения</th>
                    <th>Наименование работы</th>
                    <th>Часы</th>
                    <th>Номер заказа</th>
                    <th>Наименование заказа</th>
                    {% if current_user.permissions_level != "minimal" %}
                        <th>Дата операции</th>
                        <th style="border: none;">Действия</th>
                    {% else %}
                        <th style="border: none;">Дата операции</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ task["employee_name"] | default("-", true) }}</td>
                        <td>{{ task["personnel_number"] | default("-", true) }}</td>
                        {% set categories = {
                            "worker": "Рабочий",
                            "specialist": "Специалист",
                            "manager": "Ведущий специалист",
                        } %}
                        <td>{{ categories[task["employee_category"]] | default("-", true) }}</td>
                        <td>{{ task["department"] | default("-", true) }}</td>
                        <td>{{ task["work_name"] | default("-", true) }}</td>
                        <td class="hours" data-hours="{{ task['hours'] | default(0) }}">{{ task["hours"] | default("-", true) }}</td>
                        <td>{{ task["order_number"] | default("-", true) }}</td>
                        <td>{{ task["order_name"] | default("-", true) }}</td>
                        <td>{{ task["operation_date"] | default("-", true) }}</td>
                        {% if current_user.permissions_level != "minimal" %}
                            <td class="table-buttons-container">
                                <form method="GET" action="{{ url_for('tasks.edit_task', task_id=task['id']) }}">
                                    {% for param in request.args %}
                                        {% for value in request.args.getlist(param) %}
                                            <input type="hidden" name="{{ param }}" value="{{ value }}">
                                        {% endfor %}
                                    {% endfor %}
                                    <button type="submit" class="icon-button edit-table-task-button tooltip">
                                        <i class="fas fa-edit"></i>
                                        <span class="tooltiptext">Редактировать задание</span>
                                    </button>
                                </form>
                                <form method="POST" action="{{ url_for('tasks.delete_task', task_id=task['id']) }}">
                                    {% for param in request.args %}
                                        {% for value in request.args.getlist(param) %}
                                            <input type="hidden" name="{{ param }}" value="{{ value }}">
                                        {% endfor %}
                                    {% endfor %}
                                    <button type="submit" class="icon-button delete-table-task-button tooltip">
                                        <i class="fas fa-trash"></i>
                                        <span class="tooltiptext">Удалить задание</span>
                                    </button>
                                </form>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="hours-total-container">
        <i class="fas fa-clock"></i>
        <span class="hours-total">0.00</span>
        <button class="reset-hours-total-button">
            <i class="fas fa-times"></i>
        </button>
    </div>

    <button class="scroll-to-top">
        <i class="fas fa-arrow-up"></i>
    </button>

    <div class="modal-container">
        <div class="modal-content">
            <span class="close-modal-button"><i class="fas fa-times"></i></span>
            <p class="modal-text">Вы уверены, что хотите удалить задание?</p>
            <div class="modal-buttons">
                <button id="confirm-delete-task" class="btn btn-danger">Удалить</button>
                <button id="cancel-delete-task" class="btn btn-secondary">Отмена</button>
            </div>
        </div>
    </div>
{% endblock content %}