app/routes/auth.py
from typing import Dict, Tuple, Union

from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from flask_login import current_user, login_user, logout_user
from werkzeug.wrappers import Response

from app.db import DatabaseManager
from app.models import User
from app.utils import MESSAGES

auth_bp: Blueprint = Blueprint("auth", __name__)
db_manager: DatabaseManager = DatabaseManager()


@auth_bp.route("/", methods=["GET", "POST"])
def login() -> Union[str, Response]:
    if current_user.is_authenticated:
        return redirect(url_for("tasks.add_task"))

    if request.method == "POST":
        login: str = request.form["login"]
        password: str = request.form["password"]

        if not db_manager.users.authenticate_user(login=login, password=password):
            flash(message=MESSAGES["auth"]["invalid_credentials"], category="error")
            return render_template("auth/login.html", login=login, password=password)

        user_data: Dict[str, Union[str, int]] = db_manager.users.get_user_data_by_login(login)
        user: User = User(**user_data)
        login_user(user)

        session.permanent = True

        next_page: str = request.args.get("next")
        if not next_page or next_page.startswith("/"):
            return redirect(next_page or url_for("tasks.add_task"))

        return redirect(url_for("tasks.add_task"))
    return render_template("auth/login.html")


@auth_bp.route("/logout")
def logout() -> Response:
    logout_user()
    flash(message=MESSAGES["auth"]["logout_success"], category="info")
    return redirect(url_for("auth.login"))


@auth_bp.route("/register", methods=["GET", "POST"])
def register() -> Union[str, Response]:
    if current_user.is_authenticated:
        return redirect(url_for("tasks.add_task"))

    if request.method == "POST":
        login: str = request.form["login"]
        password: str = request.form["password"]
        password_confirm: str = request.form["password_confirm"]

        context: Dict[str, str] = {
            "login": login,
            "password": password,
            "password_confirm": password_confirm,
        }

        if not db_manager.users.is_user_existing(login=login):
            flash(MESSAGES["auth"]["registration_denied"], category="warning")
            return render_template("auth/register.html", **context)

        if not db_manager.users.is_user_enabled(login=login):
            flash(MESSAGES["auth"]["account_inactive"], category="warning")
            return render_template("auth/register.html", **context)

        if db_manager.users.is_user_registered(login=login):
            flash(MESSAGES["auth"]["user_already_registered"], category="warning")
            return render_template("auth/register.html", **context)

        if password != password_confirm:
            flash(MESSAGES["auth"]["passwords_do_not_match"], category="warning")
            return render_template("auth/register.html", **context)

        db_manager.users.register_user(login=login, password=password)
        flash(MESSAGES["auth"]["registration_success"], category="info")
        return redirect(url_for("auth.login"))
    return render_template("auth/register.html")

app/routes/control/__init__.py
from typing import Dict

from flask import Blueprint, render_template
from flask_login import current_user, login_required

from app.db import DatabaseManager
from app.utils import permission_required

from .employees import employees_bp
from .hours import hours_bp
from .logs import logs_bp
from .orders import orders_bp
from .reports import reports_bp
from .users import users_bp
from .works import works_bp

control_bp: Blueprint = Blueprint("control", __name__, url_prefix="/control")

control_bp.register_blueprint(employees_bp)
control_bp.register_blueprint(hours_bp)
control_bp.register_blueprint(logs_bp)
control_bp.register_blueprint(orders_bp)
control_bp.register_blueprint(reports_bp)
control_bp.register_blueprint(users_bp)
control_bp.register_blueprint(works_bp)

db_manager: DatabaseManager = DatabaseManager()


@control_bp.route("", methods=["GET"])
@login_required
@permission_required(["advanced"])
def index() -> str:
    context: Dict[str, int] = {
        "user_name": current_user.name,
        "orders_count": db_manager.orders.get_orders_count(),
        "employees_count": db_manager.employees.get_employees_count(),
        "tasks_count": db_manager.tasks.get_tasks_count(),
    }
    return render_template("control/index.html", **context)

app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome/font-awesome.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        <link rel="icon" href="{{ url_for('static', filename='images/logo.png') }}" type="image/x-icon">
        <title>{% block title %}{% endblock title %}</title>
    </head>

    <body data-is-factory-worker="{{ current_user.is_factory_worker }}">
        <header class="header-content">
            <a href="{{ url_for('tasks.tasks_table') }}">
                <img class="company-banner" src="{{ url_for('static', filename='images/meridian.png') }}">
            </a>
            <div class="header-buttons-container">
                {% if current_user.is_authenticated %}
                    {% if current_user.permissions_level == "advanced" %}
                        <div><a href="{{ url_for('control.index') }}" class="default-button">Панель управления</a></div>
                    {% endif %}
                    {% if current_user.permissions_level != "minimal" %}
                        <div><a href="{{ url_for('tasks.add_task') }}" class="default-button">Добавить задания</a></div>
                    {% endif %}
                    <div><a href="{{ url_for('tasks.tasks_table') }}" class="default-button">Посмотреть задания</a></div>
                    <div><a href="{{ url_for('auth.logout') }}" class="default-button">Выход из системы</a></div>
                {% endif %}
            </div>
        </header>

        <div class="content">
            {% block content %}{% endblock content %}
        </div>

        <footer class="footer-content">
            &copy; АО НПФ Меридиан
        </footer>

        <script type="module" src="{{ url_for('static', filename='js/script.js') }}"></script>
    </body>
</html>